spec/googleTranslate_preProcessOriginal_spec.js
spec/googleTranslate_processPlaceholderSpaces_Spec.js
src/chrome/manifest.json
src/firefox/manifest.json
src/googleTranslate.js
src/manifest.json

Word press translator filler peter version two

---

src/contentScript.js
src/wptf-commonTranslate.js
src/wptf-style.css

Created a pull request to merge improve-bulksave

Improve bulksave

---

README.md

So far the README.md was quite short. This PR improves it slightly. More to come as time permits...

Improved GitHub README.md

---

src/contentScript.js
src/wptf-commonTranslate.js
src/wptf-cute-alert.css
src/wptf-cute-alert.js
src/wptf-database.js
src/wptf-style.css

After this merge a conversion of the local database is necessary. We should make a not when creating the new build

Improve index db speed

---

.github/workflows/main.yml
src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-deeplTrans.js
src/wptf-functions.js
src/wptf-importfile.js
src/wptf-style.css

Merge master-enhancement V2 into master

Master enhancement v2

---

src/contentScript.js
src/wptf-commonTranslate.js
src/wptf-importfile.js
src/wptf-style.css

Merge master-enhancement-V3 into the master

Master enhancement v3

---

src/contentScript.js
src/wptf-commonTranslate.js
src/wptf-functions.js
src/wptf-importfile.js
src/wptf-style.css

New navbar wptf

---

src/contentScript.js
src/wptf-commonTranslate.js
src/wptf-functions.js
src/wptf-importfile.js
src/wptf-style.css

Discussions

---

src/contentScript.js
src/wptf-commonTranslate.js
src/wptf-options.js

Branch is working fine so can be merged

Changesrequested

---

spec/googleTranslate_postProcessTranslation_spec.js
spec/googleTranslate_processPlaceholderSpaces_Spec.js
src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/wptf-buildstats.js
src/wptf-commonTranslate.js
src/wptf-consistency.js
src/wptf-database.js
src/wptf-deeplTrans.js
src/wptf-importfile.js
src/wptf-options.html
src/wptf-options.js
src/wptf-style.css
uploads/de/export_database_de.csv
uploads/de/export_verbs_de.csv

First I fixed the wptf-options.html, which wasn't 100% according to the HTML5 standard.
Next I improved the deepl handling (previously the code was kind of spaghettified)
Finally I wrote some code to upgrade the database, creating the right indices upon update

A few change for options, deepl and db

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-options.html

This change modifies the suggestion done by DeepL or OpenAI, if necessary it improves the suggestion by replacing glossary verbs missing and other improvements

Replace copy in editor

---

src/contentScript.js
src/wptf-spellcheck.js

14-12-2023 PSS fixed an error when a non PTE translates lines, confirms them and goes into the editor

14-12-2023 PSS fixed an error created by latin texts in spelling check

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-openAITrans.js
src/wptf-options.html
src/wptf-options.js

This fixes a memory overflow problem

Solve memory issue

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-consistency.js
src/wptf-functions.js
src/wptf-options.html
src/wptf-style.css

merge this branch into the master

Add counter to indicator

---

src/background.js
src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/new-wptf-inject.js
src/wptf-commonTranslate.js
src/wptf-database.js
src/wptf-inject.js
src/wptf-openAITrans.js
src/wptf-options.html
src/wptf-options.js
src/wptf-style.css

Open ai select model

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-functions.js
src/wptf-inject.js
src/wptf-options.html
src/wptf-options.js
src/wptf-style.css

Merging changes for fetching old records, and not fetching them on pages without translations

Extended v1

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-functions.js

Merging Extended-V2 into the master

Extended v2

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-database.js
src/wptf-functions.js
src/wptf-inject.js
src/wptf-openAITrans.js
src/wptf-options.html
src/wptf-options.js
src/wptf-style.css

Extended v3

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-database.js
src/wptf-functions.js
src/wptf-importfile.js
src/wptf-options.html
src/wptf-options.js
src/wptf-style.css

Extended v4

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-style.css

Extended v6

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-deeplTrans.js
src/wptf-functions.js
src/wptf-style.css

03-09-2024 PSS removed debug statements in DeepL js 03-09-2024 PSS bumped version to 3.1.9

03-09-2024 PSS minor code improvements

---

src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate.js
src/wptf-deeplTrans.js
src/wptf-deeplTrans_org.js
src/wptf-googleTrans.js
uploads/nl/wptf-glossary.csv

Extended v10

---

src/Changelog.txt
src/background.js
src/chrome/manifest.json
src/contentScript.js
src/firefox/manifest.json
src/manifest.json
src/wptf-commonTranslate (2).js
src/wptf-commonTranslate.js
src/wptf-cute-alert.js
src/wptf-database.js
src/wptf-deeplGloss.js
src/wptf-deeplTrans.js
src/wptf-inject.js
src/wptf-options.js
src/wptf-spellcheck.js
src/wptf-style.css
uploads/nl/wptf-glossary.csv

Extended v13
